api = "0.2"

[buildpack]
  id = "com.mikusa.rust-dist"
  name = "Rust Distribution Build Pack"
  version = "0.0.2"
  homepage = "https://github.com/dmikusa/rust-dist-cnb"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  # from https://forge.rust-lang.org/infra/other-installation-methods.html#standalone
  [[metadata.dependencies]]
    id = "rust"
    name = "Rust Standalone Installer"
    version = "1.44.0"
    uri = "https://static.rust-lang.org/dist/rust-1.44.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "eaa34271b4ac4d2c281831117d4d335eed0b37fe7a34477d9855a6f1d930a624"
    source = "https://static.rust-lang.org/dist/rustc-1.44.0-src.tar.gz"
    source_256 = "bf2df62317e533e84167c5bc7d4351a99fdab1f9cd6e6ba09f51996ad8561100"
    stacks = ["io.paketo.stacks.tiny", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    
  [[metadata.dependencies]]
    id = "rust"
    name = "Rust Standalone Installer"
    version = "1.43.1"
    uri = "https://static.rust-lang.org/dist/rust-1.43.1-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "25cd71b95bba0daef56bad8c943a87368c4185b90983f4412f46e3e2418c0505"
    source = "https://static.rust-lang.org/dist/rustc-1.43.1-src.tar.gz"
    source_256 = "cde177b4a8c687da96f20de27630a1eb55c9d146a15e4c900d5c31cd3c3ac41d"
    stacks = ["io.paketo.stacks.tiny", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]