api = "0.2"

[buildpack]
  id = "com.mikusa.rust-dist"
  name = "Rust Distribution Build Pack"
  version = "0.0.3"
  homepage = "https://github.com/dmikusa/rust-dist-cnb"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  # from https://forge.rust-lang.org/infra/other-installation-methods.html#standalone
  [[metadata.dependencies]]
    id = "rust"
    name = "Rust Standalone Installer"
    version = "1.44.1"
    uri = "https://static.rust-lang.org/dist/rust-1.44.1-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "a41df89a461a580536aeb42755e43037556fba2e527dd13a1e1bb0749de28202  rust-1.44.1-x86_64-unknown-linux-gnu.tar.gz"
    source = "https://static.rust-lang.org/dist/rustc-1.44.1-src.tar.gz"
    source_256 = "7e2e64cb298dd5d5aea52eafe943ba0458fa82f2987fdcda1ff6f537b6f88473  rustc-1.44.1-src.tar.gz"
    stacks = ["io.paketo.stacks.tiny", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]

  [[metadata.dependencies]]
    id = "rust"
    name = "Rust Standalone Installer"
    version = "1.44.0"
    uri = "https://static.rust-lang.org/dist/rust-1.44.0-x86_64-unknown-linux-gnu.tar.gz"
    sha256 = "eaa34271b4ac4d2c281831117d4d335eed0b37fe7a34477d9855a6f1d930a624"
    source = "https://static.rust-lang.org/dist/rustc-1.44.0-src.tar.gz"
    source_256 = "bf2df62317e533e84167c5bc7d4351a99fdab1f9cd6e6ba09f51996ad8561100"
    stacks = ["io.paketo.stacks.tiny", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]