api = "0.2"

[buildpack]
  id = "com.mikusa.rust-dist"
  name = "Rust Install Build Pack"
  version = "0.0.1"
  homepage = "https://github.com/dmikusa/rust-dist-cnb"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"

  # from https://forge.rust-lang.org/infra/other-installation-methods.html#standalone
  [[metadata.dependencies]]
    id = "rust"
    name = "Rust Standalone Installer"
    sha256 = "25cd71b95bba0daef56bad8c943a87368c4185b90983f4412f46e3e2418c0505"
    source = "https://static.rust-lang.org/dist/rustc-1.43.1-src.tar.gz"
    source_256 = "cde177b4a8c687da96f20de27630a1eb55c9d146a15e4c900d5c31cd3c3ac41d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://static.rust-lang.org/dist/rust-1.43.1-x86_64-unknown-linux-gnu.tar.gz"
    version = "1.43.1"